vich_uploader:
    db_driver: orm

    mappings:
        announces:
            uri_prefix: /images/announces
            upload_destination: '%kernel.project_dir%/public/images/announces'
        documents:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
